### ISSUE TITLE
Failed to load class files of expansion.

### ISSUE THREAD

**Issue by Ativ3k** [Artemis-the-gr8/PlayerStatsExpansion#22]
Paper Spigot 1.19.2, PlaceholderAPI(2.11.2)
Hi, when i try load this expansion i get this error:

```
- [Fri 12:25:57 ERROR PlaceholderAPI] Failed to load class files of expansion.
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com/artemis/the/gr8/lib/kyori/adventure/text/TextComponent
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.NoClassDefFoundError: com/artemis/the/gr8/lib/kyori/adventure/text/TextComponent
    at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
    at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
    at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
    at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$7(LocalExpansionManager.java:413)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
    ... 6 more
Caused by: java.lang.ClassNotFoundException: com.artemis.the.gr8.lib.kyori.adventure.text.TextComponent
    at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    ... 11 more- [Fri 12:25:57 ERROR PlaceholderAPI] Failed to load class files of expansion.
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com/artemis/the/gr8/lib/kyori/adventure/text/TextComponent
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.NoClassDefFoundError: com/artemis/the/gr8/lib/kyori/adventure/text/TextComponent
    at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
    at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
    at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
    at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$7(LocalExpansionManager.java:413)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
    ... 6 more
Caused by: java.lang.ClassNotFoundException: com.artemis.the.gr8.lib.kyori.adventure.text.TextComponent
    at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    ... 11 more
```

**Comment by Artemis-the-gr8** [comment]
Hey! I think that is because you are still running on an older version of PlayerStats. The expansion will only work with v1.7, which I haven't released officially yet on Spigot or CurseForge, because I've been waiting to get the Expansion verified by PlaceholderAPI first. 

But the update to version 1.7 is already done, so you could get it from GitHub already (https://github.com/itHotL/PlayerStats/releases/tag/v1.7) and then it should work!

**Comment by Ativ3k** [comment]
Thanks! 
PlaceholderSign will be supported?
![image](https://user-images.githubusercontent.com/63321725/185603683-4006e4ee-6f11-430b-9497-4d3f81e49024.png)
I try add playerstats placeholder to sign but didn't work:(

**Comment by Artemis-the-gr8** [comment]
That is interesting, I haven't tested that before! 
I've tested the placeholders in chat/tab and in hologram plugins, but hadn't heard of this one before. I'll look into it and see if I can make it work!

**Comment by Artemis-the-gr8** [comment]
I've done some testing, and I suspect the issue is a limit on the side of PlaceholderSign. I looked at the PlaceholderSign code, and it seems that you cannot display anything on the sign that is longer than 16 characters. This limit includes color codes, which adds up quite quickly. If you use hex colors, the title for "Jumps", for example, would become something like "§x§f§f§d§5§2§bJumps"... With a regular chat color, it becomes "§6Jumps", which would still fit - but not if the name of the statistic is too long. And a line from a top-statistic is almost always too long, even if you turn off the dot-alligning in the config. 

Unfortunately I don't think there is much I can do about this, but I do have one (kinda) solution for you:
the number-placeholders do all seem to work. These placeholders don't use color codes, and only return a number - which almost all of the time, will be less than 16 characters. So, if you include the keyword "number" in the PlayerStats placeholder you want, you should get a functional placeholder!

![2022-08-19 14_27_27-](https://user-images.githubusercontent.com/85436257/185618468-78a0a578-dd63-439c-ab04-3d3f9b90d9ff.png)

**Comment by Ativ3k** [comment]
It's possible to disable these dots when i use `%playerstats_ top: 3, jump%`?
![image](https://user-images.githubusercontent.com/63321725/185644297-dbd6331e-edff-4398-b0b7-994bd85c2011.png)
I set `use-dots` to false but still have dots here.
![image](https://user-images.githubusercontent.com/63321725/185644473-1c7fb22e-3195-4003-abe5-2a44901af2ad.png)

example
10 chars for nickname and 6 chars for stats (max 999999) is probably enough for most player stats.

**Comment by Artemis-the-gr8** [comment]
You are right, it should be possible to disable dots that way, and I've released a new version of PlayerStats that fixes this ([version 1.7.1](https://github.com/itHotL/PlayerStats/tree/v1.7.1)).

However, due to the color codes, a top-line will still be too long for a sign. The messages are composed of 3 different parts (line-number, player-name and stat-number), and after the line-number and player-name the color resets. Even if you completely got rid of all hex-colors and replaced them with normal chat-colors, the text from your screenshot would look like this:

§63.§r §aAtiv3k:§r §b§12,608

I think the only thing that would probably work, is using the number-only-placeholder, and adding the other text around it yourself. I can add another placeholder that would let you get the player-name that belongs to a certain top-line, so then you'd get: 

%playerstats_ player-name, top: 3, jump%: %playerstats_ number, top: 3, jump%
(resulting in: "Ativ3k: 12,608")

I'll try to add the new placeholder this weekend!

**Comment by Ativ3k** [comment]
There is placeholder for total mined all blocks?

**Comment by Artemis-the-gr8** [comment]
![2022-08-20 16_14_23-](https://user-images.githubusercontent.com/85436257/185768765-0048352e-be2d-4106-88a8-1f82f6c8476d.png)
I've added a player-name placeholder in version [1.1.0](https://github.com/Artemis-the-gr8/PlayerStatsExpansion/releases/tag/v1.1.0) so you can combine these two:
`%playerstats_ only:player_name, top:1, kill_entity:zombie%`
`%playerstats_only:number, top:1, kill_entity:zombie%`
  
You'll need version [1.7.2]( https://github.com/itHotL/PlayerStats/releases/tag/v1.7.2) of PlayerStats as well to use the new placeholders. 

  
As for your other question - it is not currently possible to get the total of all blocks mined for everyone. It is planned for the future, but it requires a pretty big rewrite, so it will be a while before I get to it.
